spring:
  datasource:
    dirver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/space-time?useSSL=false
    username: root
    password: 123
  mvc:
    view:
      prefix: /jsp/
      suffix: .jsp


pagehelper:
 helperDialect: mysql
 reasonable: true
 supportMethodsArguments: true
 params: count=countSql
 
 shiro:
   session:
      #shiro session超时 设置 20分钟
       globalSessionTimeout: 1200000
   shiroFilter:
      #shiro权限分配
       loginUrl: /tologin
       successUrl: /mian
       unauthorizedUrl: /login
     #  filterChainDefinitionMap: {
     #  /bakmain: 'roles[superadmin]',
      # /tologin: logout,
       #/dologin: anon,
      # /login: anon,
      # /main: anon,
      # /**: authc}
      